version: "3.4"
services:
  falemuito-front:
    image: falemuito-front
    container_name: falemuito-front
    ports:
      - 80:80
    depends_on:
      - falemuito
  falemuito:
    image: falemuito
    container_name: falemuito-api
    ports:
      - 8083:8083
